# NumPy alapok

## Tömbök létrehozása

In [1]:
import numpy as np #numpy csomag betoltese

In [2]:
a=np.array([1,2,3,4]) #tomb (vektor, matrix, tenzor) definialasa

In [3]:
a #kiiras

array([1, 2, 3, 4])

In [4]:
a.ndim #hany dimenzioja van

1

In [5]:
a.shape #a tomb formaja (elemszam az egyes dimenziok menten)

(4,)

In [6]:
a.size #meret (osszes elem) = np.prod(a.shape)

4

In [7]:
a.dtype #adattipus (numpy tombok mindig homogenek)

dtype('int64')

In [8]:
a.itemsize #elemek merete bajtban

8

In [9]:
a.data #a tomb osszes elemet tartalmazo buffer

<read-write buffer for 0x20c4510, size 32, offset 0 at 0x7f229c0b3eb0>

In [10]:
np.array([[1, 2, 3],[4, 5, 6]], dtype=float) #matrix lebegopontos adatokkal

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [11]:
np.zeros([3,4]) #nullakkal feltoltott tomb

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [12]:
np.ones([3,4], dtype=np.int16) #egyesekkel feltoltott tomb

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [13]:
np.empty([3,4]) #inicializalatlan tomb

array([[  6.90638612e-310,   6.90638612e-310,   0.00000000e+000,
          2.96439388e-323],
       [  1.90979621e-313,   0.00000000e+000,   5.92878775e-323,
          3.18299369e-313],
       [  0.00000000e+000,   4.03179200e-313,   0.00000000e+000,
          1.08694442e-322]])

In [14]:
np.linspace(0,10,90) #90 szam egyenletesen 0-tol 10-ig

array([  0.        ,   0.11235955,   0.2247191 ,   0.33707865,
         0.4494382 ,   0.56179775,   0.6741573 ,   0.78651685,
         0.8988764 ,   1.01123596,   1.12359551,   1.23595506,
         1.34831461,   1.46067416,   1.57303371,   1.68539326,
         1.79775281,   1.91011236,   2.02247191,   2.13483146,
         2.24719101,   2.35955056,   2.47191011,   2.58426966,
         2.69662921,   2.80898876,   2.92134831,   3.03370787,
         3.14606742,   3.25842697,   3.37078652,   3.48314607,
         3.59550562,   3.70786517,   3.82022472,   3.93258427,
         4.04494382,   4.15730337,   4.26966292,   4.38202247,
         4.49438202,   4.60674157,   4.71910112,   4.83146067,
         4.94382022,   5.05617978,   5.16853933,   5.28089888,
         5.39325843,   5.50561798,   5.61797753,   5.73033708,
         5.84269663,   5.95505618,   6.06741573,   6.17977528,
         6.29213483,   6.40449438,   6.51685393,   6.62921348,
         6.74157303,   6.85393258,   6.96629213,   7.07

In [15]:
np.linspace(-2*np.pi,2*np.pi,15)

array([-6.28318531, -5.38558741, -4.48798951, -3.5903916 , -2.6927937 ,
       -1.7951958 , -0.8975979 ,  0.        ,  0.8975979 ,  1.7951958 ,
        2.6927937 ,  3.5903916 ,  4.48798951,  5.38558741,  6.28318531])

In [16]:
np.arange(15) #0-tol 14-ig

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(10000).reshape(100,100) #szamok 0-tol 9999-ig, 100x100-as matrixba rendezve

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ..., 
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

## Műveletek

In [18]:
a=np.array([20,30,40,50])
b=np.arange(4)

In [19]:
a

array([20, 30, 40, 50])

In [20]:
b

array([0, 1, 2, 3])

In [21]:
c=a-b #elemenkenti kulonbseg
c

array([20, 29, 38, 47])

In [22]:
d=b**2 #elemenkenti negyzetre emeles
d

array([0, 1, 4, 9])

In [23]:
e=10*np.sin(a) #fuggveny elemenkenti kiertekelese
e

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [24]:
f=a<35 #logikai kifejezes kiertekelese az egyes elemekre
f

array([ True,  True, False, False], dtype=bool)

In [25]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

In [26]:
A*B #matixok szorzasa elemenkent

array([[2, 0],
       [0, 4]])

In [27]:
np.dot(A,B) #rendes matrixszorzas

array([[5, 4],
       [3, 4]])

In [28]:
A.dot(B) #vagy igy is lehet

array([[5, 4],
       [3, 4]])

In [29]:
a=np.ones([2,3],dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
a*=3 #a=a*3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [31]:
a=np.random.random([2,3])
b=np.random.random([2,3]) #veletlenszamokkal feltoltott tombok, tartomany: [0, 1[

In [32]:
a

array([[ 0.55569224,  0.48339846,  0.58797556],
       [ 0.51979406,  0.20464692,  0.46405081]])

In [33]:
b

array([[ 0.85924389,  0.63239028,  0.83916402],
       [ 0.60682105,  0.60766722,  0.64964456]])

In [34]:
b+=a #b=b+a
b

array([[ 1.41493613,  1.11578874,  1.42713958],
       [ 1.12661511,  0.81231414,  1.11369536]])

In [35]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
b.sum(axis=0) #osszegzes az oszlopok menten

array([12, 15, 18, 21])

In [37]:
b.sum(axis=1) #osszegzes a sorok menten

array([ 6, 22, 38])

In [38]:
b.min() #legkisebb elem

0

In [39]:
b.min(axis=0) #legkisebb elem az egyes oszlopokban

array([0, 1, 2, 3])

In [40]:
b.max(axis=1) #legnagyobb elem az egyes sorokban

array([ 3,  7, 11])

In [41]:
b.cumsum(axis=0) #kumulalt osszeg az oszlopok menten

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

## Indexelés

In [42]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [43]:
a[5] #0-tol indexel

125

In [44]:
a[2:6] #a felso korlat nincs benne!

array([  8,  27,  64, 125])

In [45]:
a[:6:2] #elejetol kettesevel

array([ 0,  8, 64])

In [46]:
a[-1] #utolso elem

729

In [47]:
a[-2] #utolso elotti elem

512

In [48]:
a[::-1] #forditva

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [49]:
b=np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [50]:
b[2,3]

11

In [51]:
b[0:4,1] #masodik oszlop elso negy eleme

array([ 1,  5,  9, 13])

In [52]:
b[-1] #utolso sor

array([16, 17, 18, 19])

In [53]:
a=np.floor(10*np.random.random([3,4]))
a

array([[ 8.,  7.,  9.,  2.],
       [ 3.,  4.,  7.,  8.],
       [ 5.,  2.,  8.,  8.]])

In [54]:
a.reshape(1,12)[0] #matrix vektorizalasa

array([ 8.,  7.,  9.,  2.,  3.,  4.,  7.,  8.,  5.,  2.,  8.,  8.])

In [55]:
a.reshape(6,2) #6x2-es matrixsza alakitas

array([[ 8.,  7.],
       [ 9.,  2.],
       [ 3.,  4.],
       [ 7.,  8.],
       [ 5.,  2.],
       [ 8.,  8.]])

In [56]:
a.T #transzponalas

array([[ 8.,  3.,  5.],
       [ 7.,  4.,  2.],
       [ 9.,  7.,  8.],
       [ 2.,  8.,  8.]])

In [57]:
a.reshape(3,-1) #a -1-gyel jelolt elemszamot automatikusan kiszamolja (most 4)

array([[ 8.,  7.,  9.,  2.],
       [ 3.,  4.,  7.,  8.],
       [ 5.,  2.,  8.,  8.]])

In [58]:
a=np.floor(10*np.random.random([2,2]))
b=np.floor(10*np.random.random([2,2]))

In [59]:
a

array([[ 4.,  3.],
       [ 8.,  2.]])

In [60]:
b

array([[ 0.,  4.],
       [ 0.,  8.]])

In [61]:
np.concatenate([a,b],axis=0) #osszefuzes egymas ala

array([[ 4.,  3.],
       [ 8.,  2.],
       [ 0.,  4.],
       [ 0.,  8.]])

In [62]:
np.concatenate([a,b],axis=1) #osszefuzes egymas melle

array([[ 4.,  3.,  0.,  4.],
       [ 8.,  2.,  0.,  8.]])

## Objektumok, referenciák, másolás

In [63]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
b=a #referencia atadasa, nem az ertekek masolasa

In [65]:
b is a #nem ertekek, hanem referenciak osszehasonlitasa

True

In [66]:
b.shape=3,4 #reshape manualisan
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a #b-t irtuk, de a is megvaltozott!

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
c=a.view() #nezet/szemuveg (c-n keresztul latjuk a-t)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
c is a #mar nem azonos peldanyok

False

In [70]:
c.shape=1,12 #megvaltoztathatjuk az alakjat
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [71]:
a #a alakja nem valtozik

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
c[0,3]=1234
c

array([[   0,    1,    2, 1234,    4,    5,    6,    7,    8,    9,   10,
          11]])

In [73]:
a #az ertek most is megvaltozott!

array([[   0,    1,    2, 1234],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [74]:
d=a.copy() #masolni igy kell (deep copy)

In [75]:
d is a #most sem azonos peldanyok

False

In [76]:
d[0,3]=0
d

array([[ 0,  1,  2,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
a #most nem valtozott meg

array([[   0,    1,    2, 1234],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [78]:
a=np.floor(10*np.random.random([3,4]))

In [79]:
a=[]
import gc
gc.collect() #garbage collector

38